services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=overd_ose'
      - 'POSTGRES_USER=overd_ose_user'
      - 'POSTGRES_PASSWORD=overd_ose_secret'
    ports:
      - '5432:5432'
